functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключать язык интерфейса
  - На странице товара должны выводиться  название, рейтинг, цена со скидкой и без нее
  - При добавлении товара в карзину, пользователь должен оставаться на странице просмотра каталога 
  - На странице корзины пользователь должен уметь удалить товар из корзины
  - При оформлении заказа должен быть автоматический переход на страницу оплаты 
non-functional:
  -  Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Быстродействие сайта
  - Надёжное хранение персональных данных пользователя
  - Сайт должен иметь мобильную версию
  - Совместимость с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Магазин должен быть SPA-приложением, которое не перезагружает страницу
  - При фильтрации товаров должен быть  постраничный вывод
  -  Корзина должна хранится в сессии браузер
implicit:
  - Хранить персональные данные пользователя с учетом закона "О персональных данных"
  - У владельца магазина должна быть возможность задавать цену и скидки на товары 
  - При задании цены товара проверять, что цена не отрицательная 
